service: Kanbanboard

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource:
        Fn::GetAtt: 
          - EventTable
          - StreamArn

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello/world
          method: get
  db:
    handler: src/handler.db
    events:
      - http:
          path: hello/db
          method: post
  logdb:
    handler: src/handler.logdb
    events:
        - stream:
            type: dynamodb
            batchSize: 20
            startingPosition: TRIM_HORIZON
            arn:
                Fn::GetAtt:
                  - EventTable
                  - StreamArn

plugins:
  - serverless-webpack

package:
  individually: true

resources:
  Resources:
    EventTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: timestamp
            AttributeType: S
          - AttributeName: timestampSorted
            AttributeType: N
        KeySchema:
          - AttributeName: timestamp
            KeyType: HASH
          - AttributeName: timestampSorted
            KeyType: RANGE  
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 2
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    ReadCache:
      Type: AWS::ElastiCache::CacheCluster
      Properties:
        AutoMinorVersionUpgrade: true
        ClusterName: ReadCache
        Engine: redis
        NumCacheNodes: 1
        CacheNodeType: cache.t2.micro
        VpcSecurityGroupIds: 
          - sg-d92e9bb4
